name: Invincible
version: '1.0-SNAPSHOT'
main: winlyps.invincible.Invincible
api-version: '1.16'
authors: [ Winlyps ]
commands:
  invincible:
    description: Toggle invincibility for a player
    usage: /invincible <player> <on/off>
    permission: invincible.use
permissions:
  invincible.use:
    description: Allows the use of the /invincible command
    default: op